name = "redirect-worker"
compatibility_date = "2024-06-30"
main = "src/index.js"

# OR for multiple routes:
routes = [
  { pattern = "bookdubaihome.pages.dev/*" },
  # { pattern = "another-domain.com/*", zone_id = "YOUR_ZONE_ID" }  # Optional
]
